### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by wimmelstein** [REDitor/week2exercises#2]
When working with git it's as important what you put in git, and what you don't put in git. The way to control that is to put a .gitignore (yes, starts with a dot) in the root of your project, and you put in there the things you don't want. 

That would be:
*.iml
.idea
out/
target/
etc.

Creating a new repo for eacht week is not very efficient. Better to create a branch for each assignment, and separate the assignment with a /
For instance:
lesson1/exercise1
lesson1/exercise2
lesson2/exercise1

This allows you to reuse classes if that's necessary.

It's prefarable to create a main branch first with a skeleton of your project, and every time you need a clean slate, you go back to main, and branch off from there.

One thing: never merge to master

**Comment by REDitor** [comment]
I do have the .gitignore, but I usually let visual studio or in this case IntelliJ create one for me. It is inside the .idea folder. Is this the right place for it?

**Comment by wimmelstein** [comment]
Best is to have a .gitignore in the root of your project
